version: '2'
services:
  redis-node-0:
    container_name: "redis-0"
    image: docker.io/bitnami/redis-cluster:6.2
    mem_limit: 150mb
    ports:
      - "7000:6379"
    volumes:
      - /home/ntop/projects/RedisExperiment/docker/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    environment:
      - 'REDIS_NODES=redis-0 redis-1 redis-2'
      - 'REDIS_PASSWORD=bitnami'
  redis-node-1:
    container_name: "redis-1"
    image: docker.io/bitnami/redis-cluster:6.2
    mem_limit: 150mb
    ports:
      - "7001:6379"
    volumes:
      - /home/ntop/projects/RedisExperiment/docker/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    environment:
      - 'REDIS_NODES=redis-0 redis-1 redis-2'
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_CLUSTER_DNS_LOOKUP_SLEEP=5'
      - 'REDIS_CLUSTER_SLEEP_BEFORE_DNS_LOOKUP=10'
    depends_on:
      - redis-node-0
  redis-node-2:
    container_name: "redis-2"
    image: docker.io/bitnami/redis-cluster:6.2
    mem_limit: 150mb
    ports:
      - "7002:6379"
    volumes:
      - /home/ntop/projects/RedisExperiment/docker/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    environment:
      - 'REDIS_NODES=redis-0 redis-1 redis-2'
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_CLUSTER_REPLICAS=0'
      - 'REDIS_CLUSTER_DNS_LOOKUP_SLEEP=5'
      - 'REDIS_CLUSTER_SLEEP_BEFORE_DNS_LOOKUP=10'
    depends_on:
      - redis-node-0
      - redis-node-1
  demo-app:
    container_name: "demo-app"
    build:
      context: ../
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2